### Email Varify
GET http://localhost:3001/email-verify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJKaG9uIERvZSIsImVtYWlsIjoiamhvbkBkb2UuY29tIiwiaWF0IjoxNzI1MDAyMTUwLCJleHAiOjE3MjUwMDIxNjV9.ZzR9pt0CvFzxSGW1FX0FblmfQEO3JcDCFUf2ZvQoS14

### Login
POST http://localhost:3001/login
Content-Type: application/json

{
    "email": "jhon@doe.com",
    "password": "password123"
}

### Create Account
POST http://localhost:3001/register
Content-Type: application/json

{
    "name": "Jhon Doe",
    "email": "jhon@doe.com",
    "password": "password123"
}

### Logout
DELETE http://localhost:3001/logout

### Get Token
GET http://localhost:3001/token

### Get Master Tags
GET http://localhost:3001/master/tags
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJKaG9uIERvZSIsImVtYWlsIjoiamhvbkBkb2UuY29tIiwiaWF0IjoxNzI1MDAyMTUwLCJleHAiOjE3MjUwMDIxNjV9.ZzR9pt0CvFzxSGW1FX0FblmfQEO3JcDCFUf2ZvQoS14