### Login
POST http://localhost:3001/login
Content-Type: application/json

{
    "email": "jhon@gmail.com",
    "password": "jhon@gmail.com"
}

### Logout
DELETE http://localhost:3001/logout

### Create Account
POST http://localhost:3001/register
Content-Type: application/json

{
    "name": "Jhon Doe",
    "email": "jhon@doe.com",
    "password": "password123"
}

### Get Token
GET http://localhost:3001/token

### Get Master Tags
GET http://localhost:3001/master/tags
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJKaG9uIERvZSIsImVtYWlsIjoiamhvbkBnbWFpbC5jb20iLCJpYXQiOjE3MjgzNTkxOTQsImV4cCI6MTcyODM1OTIxNH0.CUuC7BcynwIn58aLfHh1NLPjBzkDwz0dG4g98SE4ypw

### Post Master Tags
POST http://localhost:3001/master/tags
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJKaG9uIERvZSIsImVtYWlsIjoiamhvbkBnbWFpbC5jb20iLCJpYXQiOjE3MjgzNzIyMDksImV4cCI6MTcyODM3MjIyNH0.rgi17zuuGzVLvBatLRzOwFPA7lgFsOmlOVVTnKklLYg
Content-Type: application/json

{
    "tag": "dsdsfsd"
}
