### Login
POST http://localhost:3001/login
Content-Type: application/json

{
    "email": "d@f.c",
    "password": "ss"
}

### Logout
DELETE http://localhost:3001/logout

### Create Account
POST http://localhost:3001/register
Content-Type: application/json

{
    "name": "Jhon Doe",
    "email": "jhon@doe.com",
    "password": "password123"
}

### Get Token
GET http://localhost:3001/token

### Get Master Tags
GET http://localhost:3001/master/tags
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJKaG9uIERvZSIsImVtYWlsIjoiamhvbkBkb2UuY29tIiwiaWF0IjoxNzI1NjkxMTE0LCJleHAiOjE3MjU2OTExMjl9.kWsNUY4tAKRTkgv9q4yvDqSwnXYEMYOExd8bdikTc0Y